version: '2'
services:
  demoysql-mysql:
    image: mysql:8.0.22
    # volumes:
    #     - ~/volumes/jhipster/demoysql/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=feedback
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=RjqpoN5oLmiD7nEJ
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
